# permissions for end users to edit mydaemonsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mydaemonset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-demo
    app.kubernetes.io/part-of: operator-demo
    app.kubernetes.io/managed-by: kustomize
  name: mydaemonset-editor-role
rules:
- apiGroups:
  - apps.ljtian.com
  resources:
  - mydaemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.ljtian.com
  resources:
  - mydaemonsets/status
  verbs:
  - get
